dataset: 
  name: "SPED"
  Root: '/mnt/d/Datasets'
  query_dir: '/SPED/Test/query/'
  refer_dir: '/SPED/Test/ref/'

results_path: 'outputs/'
seg_config_file: "pretrained_models/segformer_mit-b4_8xb2-160k_ade20k-512x512.py"
seg_checkpoint_file: "pretrained_models/segformer_mit-b4_512x512_160k_ade20k_20210728_183055-7f509d7d.pth"

model:
  nms_dist: 4
  conf_thresh: 0.015
  nn_thresh: 0.7
  weights_path: 'pretrained_models/superpoint_v1.pth'
  cuda: True
  
output_1:
  method: "AttnPatch" # ["AttnPatch", "FullGeomVeri"]
  anchor_select_policy: "segmentation"  # ["random", "largest_score", "conv_filter"]

output_2:
  method: "FullGeomVeri" # ["AttnPatch", "FullGeomVeri"]
  anchor_select_policy: "default" 